#ifndef TMDINTERPOLATOR_HPP
#define TMDINTERPOLATOR_HPP

#include <cstddef>
#include <string>
#include <vector>

// Trilinear interpolation of the Sudakov-evolved WW distribution in
// (log(x), log(k_T), eta), where
//
//   eta = log(Q^2 / Q_s^2(x)) / log(Q_max^2 / Q_s^2(x)).
//
// The table is defined only for
//
//   x_min <= x <= x_max,
//   k_min <= k_T <= k_max,
//   Q_s^2(x) <= Q^2 <= Q_max^2.
//
// Every query outside that domain returns -1. No boundary clamping or
// extrapolation is performed.
class TMDInterpolator {
public:
    TMDInterpolator() = default;
    ~TMDInterpolator() = default;

    // Load the versioned FWW3D01 binary table generated by
    // fww_table_generator.py.
    bool loadData(const std::string& filename);

    // Return F_WW(x_B, k_T, Q^2). The argument order is retained from the old
    // TMD_gluon(k_T, x_B) interface, with Q^2 added as the third coordinate.
    double TMD_gluon(double kT, double xB, double Q2) const;

    bool isInitialized() const { return initialized_; }

    double getMinKT() const { return kT_min_; }
    double getMaxKT() const { return kT_max_; }
    double getMinXB() const { return xB_min_; }
    double getMaxXB() const { return xB_max_; }
    double getMaxQ2() const { return q2_max_; }
    double getG2() const { return g2_; }

private:
    bool initialized_ = false;

    std::size_t Nx_ = 0;
    std::size_t Nk_ = 0;
    std::size_t Nq2_ = 0;

    std::vector<double> xB_grid_;
    std::vector<double> kT_grid_;
    std::vector<double> qs2_grid_;
    std::vector<double> eta_grid_;
    std::vector<double> log_xB_grid_;
    std::vector<double> log_kT_grid_;

    // Row-major order: values_[((ix * Nk_) + ik) * Nq2_ + iq].
    std::vector<double> values_;

    double xB_min_ = 0.0;
    double xB_max_ = 0.0;
    double kT_min_ = 0.0;
    double kT_max_ = 0.0;
    double q2_max_ = 0.0;
    double g2_ = 0.0;

    static std::size_t findIndex(
        const std::vector<double>& grid,
        double value);
    static bool strictlyIncreasing(const std::vector<double>& values);

    double qs2AtLogX(double log_xB) const;
    double valueAt(std::size_t ix, std::size_t ik, std::size_t iq) const;
    double trilinearInterpolate(
        double log_xB,
        double log_kT,
        double eta) const;
};

#endif // TMDINTERPOLATOR_HPP
